default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL_SIZE", 5) %>
  username: <%= ENV.fetch("DB_USER", "benchmark") %>
  password: <%= ENV.fetch("DB_PASSWORD", "benchmark") %>
  host: <%= ENV['DB_HOST'].presence || "postgres" %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  database: <%= ENV.fetch("DB_NAME", "benchmark") %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
