version: "0.2"
ignorePaths:
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/.git/**"
  - "**/target/**"
  - Cargo.toml
  - .gitignore
  - .gitattributes
dictionaryDefinitions: []
dictionaries: []
words:
  - Askama
  - chrono
  - clippy
  - cpus
  - Deque
  - dotenv
  - dotenvy
  - HEALTHCHECK
  - HTMX
  - indicatif
  - nogcio
  - rngs
  - serde
  - stdev
  - thiserror
  - Twinland
  - wrkr
ignoreWords: []
import: []
