---
type: benchmark
name: aspnetcore
language: C#
language_version: "10.0"
framework: aspnetcore
framework_version: "10.0"
tests:
  - plain_text
  - json_aggregate
tags:
  type: framework
  runtime: dotnet
  arch: async
path: benchmarks/csharp/aspnetcore

---
type: benchmark
name: aspnetcore-efcore
language: C#
language_version: "10.0"
framework: aspnetcore
framework_version: "9.0.0"
tests:
  - db_complex
tags:
  type: framework
  runtime: dotnet
  arch: async
  orm: efcore
database: postgres
path: benchmarks/csharp/aspnetcore-efcore

---
type: benchmark
name: aspnetcore-efcore-mysql
disabled: true
language: C#
language_version: "10.0"
framework: aspnetcore
framework_version: "9.0.0"
tests:
  - db_complex
tags:
  type: framework
  runtime: dotnet
  orm: efcore
  arch: async
database: mysql
path: benchmarks/csharp/aspnetcore-efcore

---
type: benchmark
name: aspnetcore-efcore-mssql
disabled: true
language: C#
language_version: "10.0"
framework: aspnetcore
framework_version: "9.0.0"
tests:
  - db_complex
tags:
  type: framework
  runtime: dotnet
  orm: efcore
  arch: async
database: mssql
path: benchmarks/csharp/aspnetcore-efcore

---
type: benchmark
name: aspnetcore-mongodb
disabled: true
language: C#
language_version: "10.0"
framework: aspnetcore
framework_version: "9.0.0"
tests:
  - db_complex
tags:
  type: framework
  runtime: dotnet
  arch: async
database: mongodb
path: benchmarks/csharp/aspnetcore-mongodb

---
type: benchmark
name: aspnetcore-npgsql
language: C#
language_version: "10.0"
framework: aspnetcore
framework_version: "9.0.0"
tests:
  - db_complex
tags:
  type: framework
  runtime: dotnet
  arch: async
database: postgres
path: benchmarks/csharp/aspnetcore-npgsql

---
type: benchmark
name: aspnetcore-mysql
disabled: true
language: C#
language_version: "10.0"
framework: aspnetcore
framework_version: "9.0.0"
tests:
  - db_complex
tags:
  type: framework
  runtime: dotnet
  arch: async
database: mysql
path: benchmarks/csharp/aspnetcore-mysql

---
type: benchmark
name: aspnetcore-mssql
disabled: true
language: C#
language_version: "10.0"
framework: aspnetcore
framework_version: "9.0.0"
tests:
  - db_complex
tags:
  type: framework
  runtime: dotnet
  arch: async
database: mssql
path: benchmarks/csharp/aspnetcore-mssql

---
type: benchmark
name: aspnetcore-mariadb
disabled: true
language: C#
language_version: "10.0"
framework: aspnetcore
framework_version: "9.0.0"
tests:
  - db_complex
tags:
  type: framework
  runtime: dotnet
  arch: async
database: mariadb
path: benchmarks/csharp/aspnetcore-mysql

---
type: benchmark
name: aspnetcore-efcore-mariadb
disabled: true
language: C#
language_version: "10.0"
framework: aspnetcore
framework_version: "9.0.0"
tests:
  - db_complex
tags:
  type: framework
  runtime: dotnet
  orm: efcore
  arch: async
database: mariadb
path: benchmarks/csharp/aspnetcore-efcore


---
type: benchmark
name: aspnetcore-grpc
language: C#
language_version: "10.0"
framework: aspnetcore
framework_version: "10.0"
tests:
  - grpc_aggregate
tags:
  type: framework
  runtime: dotnet
  arch: async
path: benchmarks/csharp/aspnetcore-grpc
