---
type: benchmark
name: spring-boot-jpa-postgres
language: Java
language_version: "25"
framework: spring-boot
framework_version: "4.0.1"
database: postgres
tests:
  - plain_text
  - json_aggregate
  - db_complex
tags:
  type: full-stack
  runtime: jvm
  arch: thread-per-request
  orm: jpa
path: benchmarks/java/spring-boot-jpa-postgres

---
type: benchmark
name: quarkus-reactive
language: Java
language_version: "25"
framework: quarkus
framework_version: "3.17.6"
tests:
  - plain_text
  - json_aggregate
tags:
  type: full-stack
  runtime: jvm
  arch: reactive
path: benchmarks/java/quarkus-reactive


---
type: benchmark
name: quarkus-grpc
language: Java
language_version: "25"
framework: quarkus
framework_version: "3.17.6"
tests:
  - grpc_aggregate
tags:
  type: micro-framework
  runtime: jvm
  arch: reactive
path: benchmarks/java/quarkus-grpc
