---
type: benchmark
name: express
language: JavaScript
language_version: "25"
framework: express
framework_version: "5.2.1"
tests:
  - plain_text
  - static_files
  - json_aggregate
tags:
  type: micro-framework
  runtime: nodejs
  arch: event-loop
path: benchmarks/javascript/express

---
type: benchmark
name: fastify
language: JavaScript
language_version: "25"
framework: fastify
framework_version: "5.6.2"
tests:
  - plain_text
  - static_files
  - json_aggregate
tags:
  type: micro-framework
  runtime: nodejs
  arch: event-loop
path: benchmarks/javascript/fastify

---
type: benchmark
name: hono
language: JavaScript
language_version: "Bun 1.3.5"
framework: hono
framework_version: "4.11.2"
tests:
  - plain_text
  - json_aggregate
tags:
  type: micro-framework
  runtime: bun
  arch: event-loop
path: benchmarks/javascript/hono

---
type: benchmark
name: fastify-pg
language: JavaScript
language_version: "25.2.1"
framework: fastify
framework_version: "5.6.2"
tests:
  - db_complex
tags:
  type: micro-framework
  runtime: nodejs
  arch: event-loop
database: postgres
path: benchmarks/javascript/fastify-pg

---
type: benchmark
name: elysia-pg
language: JavaScript
language_version: "Bun 1.1.42"
framework: elysia
framework_version: "1.2.9"
tests:
  - plain_text
  - json_aggregate
  - db_complex
tags:
  type: micro-framework
  runtime: bun
  arch: event-loop
database: postgres
path: benchmarks/javascript/elysia-pg

---
type: benchmark
name: fastify-prisma
language: JavaScript
language_version: "22"
framework: fastify
framework_version: "5.6.2"
tests:
  - db_complex
tags:
  type: micro-framework
  runtime: nodejs
  arch: event-loop
  orm: prisma
database: postgres
path: benchmarks/javascript/fastify-prisma


---
type: benchmark
name: grpc-js
language: JavaScript
language_version: "25"
framework: grpc
framework_version: "1.12.0"
tests:
  - grpc_aggregate
tags:
  type: micro-framework
  runtime: nodejs
  arch: event-loop
path: benchmarks/javascript/grpc-js
