---
type: benchmark
name: laravel
language: PHP
language_version: "8.5"
framework: laravel
framework_version: "12.46.0"
tests:
  - plain_text
  - static_files
  - json_aggregate
  - db_complex
tags:
  type: full-stack
  runtime: vm
  arch: sync
database: postgres
path: benchmarks/php/laravel

---
type: benchmark
name: hyperf-swoole-pg
language: PHP
language_version: "8.2"
framework: hyperf
framework_version: "3.1.0"
tests:
  - plain_text
  - json_aggregate
  - db_complex
tags:
  type: micro-framework
  runtime: swoole
  arch: coroutine
database: postgres
path: benchmarks/php/hyperf-swoole-pg

