---
type: benchmark
name: nginx
language: C
language_version: "C11"
framework: nginx
framework_version: "1.29.4"
tests:
  - plain_text
tags:
  platform: nginx
path: benchmarks/c/nginx

---
type: benchmark
name: haproxy
language: C
language_version: "C11"
framework: haproxy
framework_version: "2.8.4"
tests:
  - plain_text
tags:
  platform: haproxy
path: benchmarks/c/haproxy