- name: aspnetcore
  language: C#
  language_version: "10.0"
  framework: aspnetcore
  framework_version: "10.0"
  tests:
    - hello_world
    - json
    - static_files_small
    - static_files_medium
    - static_files_large
  tags:
    platform: dotnet
    dotnet: "10.0"
  path: benchmarks/csharp/aspnetcore

- name: aspnetcore-npgsql
  language: C#
  language_version: "10.0"
  framework: aspnetcore
  framework_version: "10.0"
  tests:
    - db_read_one
    - db_read_paging
    - db_write
  tags:
    platform: dotnet
    dotnet: "10.0"
    db_lib: npgsql
    db_lib_version: "10.0.1"
  path: benchmarks/csharp/aspnetcore-npgsql
  database: postgres

- name: aspnetcore-mysql
  language: C#
  language_version: "10.0"
  framework: aspnetcore
  framework_version: "10.0"
  tests:
    - db_read_one
    - db_read_paging
    - db_write
  tags:
    platform: dotnet
    dotnet: "10.0"
    db_lib: mysqlconnector
    db_lib_version: "2.5.0"
  path: benchmarks/csharp/aspnetcore-mysql
  database: mysql

- name: aspnetcore-mssql
  language: C#
  language_version: "10.0"
  framework: aspnetcore
  framework_version: "10.0"
  tests:
    - db_read_one
    - db_read_paging
    - db_write
  tags:
    platform: dotnet
    dotnet: "10.0"
    db_lib: sqlclient
    db_lib_version: "6.1.3"
  path: benchmarks/csharp/aspnetcore-mssql
  database: mssql

- name: aspnetcore-efcore-postgres
  language: C#
  language_version: "10.0"
  framework: aspnetcore
  framework_version: "10.0"
  tests:
    - db_read_one
    - db_read_paging
    - db_write
    - tweet_service
  tags:
    platform: dotnet
    dotnet: "10.0"
    orm: efcore
    orm_version: "10.0.0"
    db_lib: npgsql-efcore
    db_lib_version: "10.0.0"
  path: benchmarks/csharp/aspnetcore-efcore
  database: postgres

- name: aspnetcore-efcore-mysql
  language: C#
  language_version: "10.0"
  framework: aspnetcore
  framework_version: "10.0"
  tests:
    - db_read_one
    - db_read_paging
    - db_write
    - tweet_service
  tags:
    platform: dotnet
    dotnet: "10.0"
    orm: efcore
    orm_version: "10.0.0"
    db_lib: mysql-efcore
    db_lib_version: "10.0.0-rc"
  path: benchmarks/csharp/aspnetcore-efcore
  database: mysql

- name: aspnetcore-efcore-mssql
  language: C#
  language_version: "10.0"
  framework: aspnetcore
  framework_version: "10.0"
  tests:
    - db_read_one
    - db_read_paging
    - db_write
    - tweet_service
  tags:
    platform: dotnet
    dotnet: "10.0"
    orm: efcore
    orm_version: "10.0.0"
    db_lib: mssql-efcore
    db_lib_version: "10.0.0"
  path: benchmarks/csharp/aspnetcore-efcore
  database: mssql
