- name: aspnetcore
  language: C#
  language_version: "10.0"
  framework: aspnetcore
  framework_version: "10.0"
  tests:
    - hello_world
    - json
    - static_files_small
    - static_files_medium
    - static_files_large
  tags:
    platform: dotnet
    dotnet: "10.0"
  path: benchmarks/csharp/aspnetcore

- name: aspnetcore-npgsql
  language: C#
  language_version: "10.0"
  framework: aspnetcore
  framework_version: "10.0"
  tests:
    - db_read_one
    - db_read_paging
    - db_write
  tags:
    platform: dotnet
    dotnet: "10.0"
    db_lib: npgsql
    db_lib_version: "10.0.1"
  path: benchmarks/csharp/aspnetcore-npgsql
  database: postgres

- name: aspnetcore-mysql
  language: C#
  language_version: "10.0"
  framework: aspnetcore
  framework_version: "10.0"
  tests:
    - db_read_one
    - db_read_paging
    - db_write
  tags:
    platform: dotnet
    dotnet: "10.0"
    db_lib: mysqlconnector
    db_lib_version: "2.5.0"
  path: benchmarks/csharp/aspnetcore-mysql
  database: mysql

- name: aspnetcore-mariadb
  language: C#
  language_version: "10.0"
  framework: aspnetcore
  framework_version: "10.0"
  tests:
    - db_read_one
    - db_read_paging
    - db_write
  tags:
    platform: dotnet
    dotnet: "10.0"
    db_lib: mysqlconnector
    db_lib_version: "2.5.0"
  path: benchmarks/csharp/aspnetcore-mysql
  database: mariadb

- name: aspnetcore-mssql
  language: C#
  language_version: "10.0"
  framework: aspnetcore
  framework_version: "10.0"
  tests:
    - db_read_one
    - db_read_paging
    - db_write
  tags:
    platform: dotnet
    dotnet: "10.0"
    db_lib: sqlclient
    db_lib_version: "6.1.3"
  path: benchmarks/csharp/aspnetcore-mssql
  database: mssql

- name: aspnetcore-efcore-postgres
  language: C#
  language_version: "9.0"
  framework: aspnetcore
  framework_version: "9.0"
  tests:
    - db_read_one
    - db_read_paging
    - db_write
    - tweet_service
  tags:
    platform: dotnet
    dotnet: "9.0"
    orm: efcore
    orm_version: "9.0.0"
    db_lib: npgsql-efcore
    db_lib_version: "9.0.2"
  path: benchmarks/csharp/aspnetcore-efcore
  database: postgres

- name: aspnetcore-efcore-mysql
  language: C#
  language_version: "9.0"
  framework: aspnetcore
  framework_version: "9.0"
  tests:
    - db_read_one
    - db_read_paging
    - db_write
    - tweet_service
  tags:
    platform: dotnet
    dotnet: "9.0"
    orm: efcore
    orm_version: "9.0.0"
    db_lib: pomelo-efcore-mysql
    db_lib_version: "9.0.0"
  path: benchmarks/csharp/aspnetcore-efcore
  database: mysql

- name: aspnetcore-efcore-mariadb
  language: C#
  language_version: "9.0"
  framework: aspnetcore
  framework_version: "9.0"
  tests:
    - db_read_one
    - db_read_paging
    - db_write
    - tweet_service
  tags:
    platform: dotnet
    dotnet: "9.0"
    orm: efcore
    orm_version: "9.0.0"
    db_lib: pomelo-efcore-mysql
    db_lib_version: "9.0.0"
  path: benchmarks/csharp/aspnetcore-efcore
  database: mariadb

- name: aspnetcore-efcore-mssql
  language: C#
  language_version: "9.0"
  framework: aspnetcore
  framework_version: "9.0"
  tests:
    - db_read_one
    - db_read_paging
    - db_write
    - tweet_service
  tags:
    platform: dotnet
    dotnet: "9.0"
    orm: efcore
    orm_version: "9.0.0"
    db_lib: mssql-efcore
    db_lib_version: "9.0.0"
  path: benchmarks/csharp/aspnetcore-efcore
  database: mssql

- name: aspnetcore-mongodb
  language: C#
  language_version: "10.0"
  framework: aspnetcore
  framework_version: "10.0"
  tests:
    - db_read_one
    - db_read_paging
    - db_write
    - tweet_service
  tags:
    platform: dotnet
    dotnet: "10.0"
    db_lib: mongodb-driver
    db_lib_version: "3.5.2"
  path: benchmarks/csharp/aspnetcore-mongodb
  database: mongodb

- name: axum
  language: Rust
  language_version: "1.92"
  framework: axum
  framework_version: "0.8.8"
  tests:
    - hello_world
    - json
    - static_files_small
    - static_files_medium
    - static_files_large
  tags:
    platform: axum
  path: benchmarks/rust/axum

- name: axum-sqlx-postgres
  language: Rust
  language_version: "1.92"
  framework: axum
  framework_version: "0.8.8"
  tests:
    - db_read_one
    - db_read_paging
    - db_write
    - tweet_service
  tags:
    platform: rust
    db_lib: sqlx
    db_lib_version: "0.8.6"
  path: benchmarks/rust/axum-sqlx-postgres
  database: postgres

- name: gin
  language: Go
  language_version: "1.25.5"
  framework: gin
  framework_version: "1.11.0"
  tests:
    - hello_world
    - json
    - static_files_small
    - static_files_medium 
    - static_files_large
  tags:
    platform: go
  path: benchmarks/go/gin

- name: gin-pgx
  language: Go
  language_version: "1.25.5"
  framework: gin
  framework_version: "1.11.0"
  tests:
    - db_read_one
    - db_read_paging
    - db_write
    - tweet_service
  tags:
    platform: go
    db_lib: pgx
    db_lib_version: "5.7.6"
  path: benchmarks/go/gin-pgx
  database: postgres

- name: fastify
  language: JS
  language_version: "25.2.1"
  framework: fastify
  framework_version: "5.6.2"
  tests:
    - hello_world
    - json
    - static_files_small
    - static_files_medium
    - static_files_large
  tags:
    platform: nodejs
    nodejs: "25.2.1"
  path: benchmarks/javascript/fastify

- name: fastify-pg
  language: JS
  language_version: "25.2.1"
  framework: fastify
  framework_version: "5.6.2"
  tests:
    - db_read_one
    - db_read_paging
    - db_write
    - tweet_service
  tags:
    platform: nodejs
    nodejs: "25.2.1"
    db_lib: pg
    db_lib_version: "8.16.3"
  path: benchmarks/javascript/fastify-pg
  database: postgres

- name: fastapi
  language: Python
  language_version: "3.14.2"
  framework: fastapi
  framework_version: "0.127.0"
  tests:
    - hello_world
    - json
    - static_files_small
    - static_files_medium
    - static_files_large
  tags:
    platform: python
    python: "3.14.2"
  path: benchmarks/python/fastapi

- name: fastapi-pg
  language: Python
  language_version: "3.14.2"
  framework: fastapi
  framework_version: "0.127.0"
  tests:
    - db_read_one
    - db_read_paging
    - db_write
    - tweet_service
  tags:
    platform: python
    python: "3.14.2"
    db_lib: asyncpg
    db_lib_version: "0.31.0"
  path: benchmarks/python/fastapi-pg
  database: postgres

- name: ktor
  language: Kotlin
  language_version: "2.3.0"
  framework: ktor
  framework_version: "3.3.3"
  tests:
    - hello_world
    - json
    - static_files_small
    - static_files_medium
    - static_files_large
  tags:
    platform: jvm
    jvm: "25.0.1_8"
    kotlin: "2.3.0"
  path: benchmarks/kotlin/ktor

- name: ktor-jdbc-postgres
  language: Kotlin
  language_version: "2.3.0"
  framework: ktor
  framework_version: "3.3.3"
  tests:
    - db_read_one
    - db_read_paging
    - db_write
    - tweet_service
  tags:
    platform: jvm
    jvm: "25.0.1_8"
    kotlin: "2.3.0"
    db_lib: jdbc
    db_lib_version: "42.7.8"
  path: benchmarks/kotlin/ktor-jdbc-postgres
  database: postgres

- name: nginx
  language: C
  language_version: "C11"
  framework: nginx
  framework_version: "1.29.4"
  tests:
    - hello_world
    - static_files_small
    - static_files_medium
    - static_files_large
  tags:
    platform: nginx
  path: benchmarks/c/nginx

- name: envoy
  language: C++
  language_version: "17"
  framework: envoy
  framework_version: "1.36.4"
  tests:
    - hello_world
  tags:
    platform: envoy
  path: benchmarks/cpp/envoy

- name: haproxy
  language: C
  language_version: "C11"
  framework: haproxy
  framework_version: "3.3.1"
  tests:
    - hello_world
  tags:
    platform: haproxy
  path: benchmarks/c/haproxy

- name: caddy
  language: Go
  language_version: "1.23"
  framework: caddy
  framework_version: "2.10.2"
  tests:
    - hello_world
    - static_files_small
    - static_files_medium
    - static_files_large
  tags:
    platform: caddy
  path: benchmarks/go/caddy

- name: pingora
  language: Rust
  language_version: "1.92"
  framework: pingora
  framework_version: "0.6.0"
  tests:
    - hello_world
  tags:
    platform: pingora
  path: benchmarks/rust/pingora

- name: openresty
  language: Lua
  language_version: "5.1"
  framework: nginx
  framework_version: "1.27.1.2"
  tests:
    - hello_world
    - json
  tags:
    platform: nginx
  path: benchmarks/lua/nginx

- name: spring-boot-jpa-postgres
  language: Java
  language_version: "23"
  framework: spring-boot
  framework_version: "4.0.1"
  tests:
    - hello_world
    - json
    - static_files_small
    - static_files_medium
    - static_files_large
    - db_read_one
    - db_read_paging
    - db_write
    - tweet_service
  tags:
    platform: java
    java: "23"
    orm: hibernate
  path: benchmarks/java/spring-boot-jpa-postgres
  database: postgres

- name: express
  language: JS
  language_version: "25.2.1"
  framework: express
  framework_version: "5.2.1"
  tests:
    - hello_world
    - static_files_small
    - static_files_medium
    - static_files_large
  tags:
    platform: nodejs
    nodejs: "22.12.0"
  path: benchmarks/javascript/express

- name: actix-web
  language: Rust
  language_version: "1.92"
  framework: actix-web
  framework_version: "4.12.1"
  tests:
    - hello_world
    - static_files_small
    - static_files_medium
    - static_files_large
  tags:
    platform: rust
  path: benchmarks/rust/actix-web

- name: fiber
  language: Go
  language_version: "1.25.5"
  framework: fiber
  framework_version: "2.52.10"
  tests:
    - hello_world
    - static_files_small
    - static_files_medium
    - static_files_large
  tags:
    platform: go
  path: benchmarks/go/fiber

- name: hono
  language: JS
  language_version: "1.3.5"
  framework: hono
  framework_version: "4.11.2"
  tests:
    - hello_world
    - json
    - static_files_small
    - static_files_medium
    - static_files_large
  tags:
    platform: bun
    bun: "1.3.5"
  path: benchmarks/javascript/hono

