type: framework
name: stdlib
language: Go
url: https://golang.org/pkg/net/http/

---
type: framework
name: std
language: JS
url: https://nodejs.org/api/http.html

---
type: framework
name: axum
language: Rust
url: https://github.com/tokio-rs/axum

---
type: framework
name: actix-web
language: Rust
url: https://actix.rs/

---
type: framework
name: aspnetcore
language: C#
url: https://dotnet.microsoft.com/apps/aspnet

---
type: framework
name: gin
language: Go
url: https://gin-gonic.com/

---
type: framework
name: fiber
language: Go
url: https://gofiber.io/

---
type: framework
name: fastify
language: JS
url: https://www.fastify.io/

---
type: framework
name: fastapi
language: Python
url: https://fastapi.tiangolo.com/

---
type: framework
name: ktor
language: Kotlin
url: https://ktor.io/

---
type: framework
name: nginx
language: C
url: https://nginx.org/

---
type: framework
name: envoy
language: C++
url: https://www.envoyproxy.io/

---
type: framework
name: haproxy
language: C
url: https://www.haproxy.org/

---
type: framework
name: caddy
language: Go
url: https://caddyserver.com/

---
type: framework
name: pingora
language: Rust
url: https://github.com/cloudflare/pingora

---
type: framework
name: traefik
language: Go
url: https://traefik.io/

---
type: framework
name: openresty
language: Lua
url: https://openresty.org/

---
type: framework
name: spring-boot
language: Java
url: https://spring.io/projects/spring-boot

---
type: framework
name: express
language: JS
url: https://expressjs.com/

---
type: framework
name: hono
language: JS
url: https://hono.dev/

