- name: Go
  url: https://golang.org
  frameworks:
    - name: stdlib
      path: benchmarks/go/std
      url: https://golang.org/pkg/net/http/
      tags:
        go: "1.21"
        platform: go

- name: JS
  url: https://nodejs.org
  frameworks:
    - name: std
      path: benchmarks/js/std
      url: https://nodejs.org/api/http.html
      tags:
        node: "25.2.1"
        platform: node