name: Test Java Benchmark

on:
  push:
    branches: [ "main" ]
    paths:
      - 'benchmarks/java/**'
      - 'benchmarks_db/**'
      - 'config/benchmarks.yaml'
      - '.github/workflows/reusable-benchmark-test.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'benchmarks/java/**'
      - 'benchmarks_db/**'
      - 'config/benchmarks.yaml'
      - '.github/workflows/reusable-benchmark-test.yml'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: spring-boot-jpa-postgres
            framework_path: benchmarks/java/spring-boot-jpa-postgres
            image_tag: wfb-java-spring-boot-jpa-postgres
            tests: hello_world,json,static_files_small,static_files_medium,static_files_large,db_read_one,db_read_paging,db_write,tweet_service
            database: postgres

    name: ${{ matrix.name }}
    uses: ./.github/workflows/reusable-benchmark-test.yml
    with:
      framework_path: ${{ matrix.framework_path }}
      image_tag: ${{ matrix.image_tag }}
      tests: ${{ matrix.tests }}
      database: ${{ matrix.database }}
