name: Test C# Benchmark

on:
  push:
    branches: [ "main" ]
    paths:
      - 'benchmarks/csharp/**'
      - 'benchmarks_db/**'
      - 'config/benchmarks.yaml'
      - '.github/workflows/reusable-benchmark-test.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'benchmarks/csharp/**'
      - 'benchmarks_db/**'
      - 'config/benchmarks.yaml'
      - '.github/workflows/reusable-benchmark-test.yml'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: aspnetcore
          - name: aspnetcore-npgsql
          - name: aspnetcore-mysql
          - name: aspnetcore-mariadb
          - name: aspnetcore-mssql
          - name: aspnetcore-mongodb
          - name: aspnetcore-efcore
          - name: aspnetcore-efcore-mysql
          - name: aspnetcore-efcore-mariadb
          - name: aspnetcore-efcore-mssql

    name: ${{ matrix.name }}
    uses: ./.github/workflows/reusable-benchmark-test.yml
    with:
      benchmark: ${{ matrix.name }}
