name: Test JS Benchmark

on:
  push:
    branches: [ "main" ]
    paths:
      - 'benchmarks/js/std/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'benchmarks/js/std/**'

jobs:
  test:
    uses: ./.github/workflows/reusable-benchmark-test.yml
    with:
      framework_path: benchmarks/js/std
      image_tag: wfb-js-std
