name: Test Rust Benchmark

on:
  push:
    branches: [ "main" ]
    paths:
      - 'benchmarks/rust/axum/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'benchmarks/rust/axum/**'

jobs:
  test:
    uses: ./.github/workflows/reusable-benchmark-test.yml
    with:
      framework_path: benchmarks/rust/axum
      image_tag: wfb-rust-axum
