name: Test C# Benchmark

on:
  push:
    branches: [ "main" ]
    paths:
      - 'benchmarks/csharp/aspnetcore/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'benchmarks/csharp/aspnetcore/**'

jobs:
  test:
    uses: ./.github/workflows/reusable-benchmark-test.yml
    with:
      framework_path: benchmarks/csharp/aspnetcore
      image_tag: wfb-aspnetcore
